# Generated by Django 4.2.30 on 2026-08-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_device_id_profile_telephone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=100, unique=True)),
                ('valeur', models.TextField(blank=True, default='')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
