# Generated by Django 4.2.30 on 2026-09-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_parametre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('agent', 'Agent Terrain'), ('restauration', 'Equipe Restauration'), ('technicien', 'Technicien Maintenance'), ('menage', 'Equipe Ménage'), ('boutique', 'Bar & Boutique'), ('securite', 'Sécurité'), ('medical', 'Médical'), ('hse', 'HSE / QHSE'), ('accueil', "Agent d'accueil"), ('manager', 'Manager / Responsable')], default='agent', max_length=20),
        ),
    ]
