# Generated by Django 4.2.30 on 2026-09-19 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_bootstrap_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportPlanifie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('frequence', models.CharField(choices=[('quotidien', 'Quotidien'), ('hebdomadaire', 'Hebdomadaire'), ('mensuel', 'Mensuel')], default='hebdomadaire', max_length=20)),
                ('jour_semaine', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], null=True)),
                ('jour_mois', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('heure', models.TimeField(default='07:00')),
                ('destinataires', models.JSONField(blank=True, default=list)),
                ('actif', models.BooleanField(default=True)),
                ('derniere_execution', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
