# Generated by Django 4.2.30 on 2026-09-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rapportplanifie'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(db_index=True, max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('expire_le', models.DateTimeField()),
                ('utilise', models.BooleanField(default=False)),
                ('tentatives', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
