# Generated by Django 4.2.30 on 2026-09-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_bootstrap_jmp_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire', models.CharField(db_index=True, help_text='Numéro au format local (celui déjà stocké dans Personnel.telephone)', max_length=30)),
                ('pays', models.CharField(default='CI', max_length=2)),
                ('canal', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='sms', max_length=10)),
                ('type_message', models.CharField(choices=[('otp', 'Code de connexion (OTP)'), ('identifiants', 'Identifiants de compte'), ('notification', 'Notification'), ('alerte', 'Alerte'), ('rappel', 'Rappel'), ('campagne', 'Campagne'), ('systeme', 'Système')], default='systeme', max_length=20)),
                ('fournisseur', models.CharField(blank=True, default='', help_text='Code du fournisseur utilisé (test, twilio, orange, prosms, hsms, meta...)', max_length=30)),
                ('fournisseur_message_id', models.CharField(blank=True, default='', help_text='Identifiant renvoyé par le fournisseur, pour le suivi/webhook', max_length=100)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('sending', 'Envoi en cours'), ('sent', 'Envoyé'), ('delivered', 'Livré'), ('failed', 'Échec'), ('rejected', 'Rejeté'), ('expired', 'Expiré')], db_index=True, default='pending', max_length=20)),
                ('erreur', models.TextField(blank=True, default='')),
                ('campagne', models.CharField(blank=True, default='', help_text='Regroupement pour un envoi en masse — vide pour un envoi individuel', max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['campagne', 'date_creation'], name='accounts_sm_campagn_9e8040_idx')],
            },
        ),
    ]
