# Generated by Django 4.2.30 on 2026-09-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_smsmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smsmessage",
            name="canal",
            field=models.CharField(
                choices=[("sms", "SMS"), ("whatsapp", "WhatsApp"), ("email", "Email")],
                default="sms",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="smsmessage",
            name="destinataire",
            field=models.CharField(
                db_index=True,
                help_text="Numéro au format local (Personnel.telephone) pour sms/whatsapp, adresse email (Personnel.email) pour le canal email — 254 = longueur max RFC 5321 d'une adresse email",
                max_length=254,
            ),
        ),
    ]
