# Generated by Django 4.2.30 on 2026-10-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_synchroniser_profils"),
    ]

    operations = [
        migrations.AddField(
            model_name="rapportplanifie",
            name="options",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="rapportplanifie",
            name="type_rapport",
            field=models.CharField(default="synthese", max_length=20),
        ),
    ]
