# Generated by Django 6.0.5 on 2026-05-06 08:44

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('societe', models.CharField(max_length=100)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('type_personnel', models.CharField(choices=[('roxgold', 'Agent Roxgold'), ('sous_traitant', 'Sous-traitant'), ('visiteur', 'Visiteur temporaire')], default='roxgold', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('qr_code_data', models.TextField(blank=True)),
                ('qr_code_string', models.CharField(blank=True, max_length=500)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Personnel',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPersonnel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('societe', models.CharField(max_length=100)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('type_personnel', models.CharField(choices=[('roxgold', 'Agent Roxgold'), ('sous_traitant', 'Sous-traitant'), ('visiteur', 'Visiteur temporaire')], default='roxgold', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('qr_code_data', models.TextField(blank=True)),
                ('qr_code_string', models.CharField(blank=True, max_length=500)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Personnel',
                'verbose_name_plural': 'historical Personnels',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='batiment',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batiments', to='residences.personnel'),
        ),
        migrations.AddField(
            model_name='historicalbatiment',
            name='personnel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='residences.personnel'),
        ),
    ]
