# Generated by Django 6.0.5 on 2026-05-06 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0002_personnel_historicalpersonnel_batiment_personnel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batiment',
            options={'ordering': ['bloc', 'residence'], 'verbose_name': 'Batiment'},
        ),
        migrations.AlterModelOptions(
            name='historicalbatiment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Batiment', 'verbose_name_plural': 'historical Batiments'},
        ),
        migrations.RemoveField(
            model_name='batiment',
            name='date_affectation',
        ),
        migrations.RemoveField(
            model_name='historicalbatiment',
            name='date_affectation',
        ),
        migrations.AddField(
            model_name='batiment',
            name='date_arrivee',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batiment',
            name='date_depart',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbatiment',
            name='date_arrivee',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbatiment',
            name='date_depart',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OccupationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupant_nom', models.CharField(max_length=200)),
                ('societe', models.CharField(blank=True, max_length=100)),
                ('date_arrivee', models.DateField()),
                ('date_depart', models.DateField(blank=True, null=True)),
                ('motif_depart', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='residences.batiment')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_residence', to='residences.personnel')),
            ],
            options={
                'verbose_name': 'Historique occupation',
                'ordering': ['-date_arrivee'],
            },
        ),
    ]
