# Generated by Django 6.0.5 on 2026-05-06 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0003_alter_batiment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batiment',
            options={'ordering': ['residence'], 'verbose_name': 'Batiment'},
        ),
        migrations.AlterModelOptions(
            name='occupationhistory',
            options={'ordering': ['-date_arrivee']},
        ),
        migrations.AddField(
            model_name='historicalpersonnel',
            name='login_genere',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalpersonnel',
            name='password_genere',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalpersonnel',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personnel',
            name='login_genere',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personnel',
            name='password_genere',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personnel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to=settings.AUTH_USER_MODEL),
        ),
    ]
