# Generated by Django 4.2.30 on 2026-05-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0005_demande_historicaldemande'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonnel',
            name='date_expiration',
            field=models.DateTimeField(blank=True, help_text='Expiration accès temporaire', null=True),
        ),
        migrations.AddField(
            model_name='historicalpersonnel',
            name='est_temporaire',
            field=models.BooleanField(default=False, help_text='Accès temporaire 24h'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='date_expiration',
            field=models.DateTimeField(blank=True, help_text='Expiration accès temporaire', null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='est_temporaire',
            field=models.BooleanField(default=False, help_text='Accès temporaire 24h'),
        ),
    ]
