# Generated by Django 6.0.5 on 2026-05-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0005_demande_historicaldemande'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonnel',
            name='role_camp',
            field=models.CharField(blank=True, default='agent', help_text='Rôle dans le camp', max_length=20),
        ),
        migrations.AddField(
            model_name='personnel',
            name='role_camp',
            field=models.CharField(blank=True, default='agent', help_text='Rôle dans le camp', max_length=20),
        ),
    ]
