# Generated by Django 4.2.30 on 2026-08-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0007_historicalpersonnel_profil_personnel_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='InductionCampConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Camp Résidentiel', max_length=200)),
                ('site', models.CharField(blank=True, default='', max_length=200)),
                ('capacite', models.PositiveIntegerField(default=0)),
                ('superficie', models.CharField(blank=True, default='', max_length=50)),
                ('altitude', models.CharField(blank=True, default='', max_length=50)),
                ('duree_parcours_min', models.PositiveIntegerField(default=15)),
                ('date_maj', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Induction Camp',
            },
        ),
        migrations.CreateModel(
            name='InductionInfra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('emoji', models.CharField(blank=True, default='🏠', max_length=10)),
                ('couleur', models.CharField(blank=True, default='#3b82f6', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=list)),
                ('photo_base64', models.TextField(blank=True, default='')),
                ('photo_mime', models.CharField(blank=True, default='image/jpeg', max_length=50)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Infrastructure (Induction)',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InductionQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('bonne_reponse', models.PositiveSmallIntegerField(default=0)),
                ('explication', models.TextField(blank=True, default='')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question Quiz (Induction)',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InductionRegle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('emoji', models.CharField(blank=True, default='📋', max_length=10)),
                ('niveau', models.CharField(choices=[('critique', 'Critique'), ('important', 'Important'), ('standard', 'Standard')], default='standard', max_length=20)),
                ('texte', models.TextField()),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Règle (Induction)',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.AddField(
            model_name='historicalpersonnel',
            name='numero_whatsapp',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='historicalpersonnel',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='personnel',
            name='numero_whatsapp',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='personnel',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalpersonnel',
            name='profil',
            field=models.CharField(blank=True, choices=[('admin', 'Administrateur'), ('agent', 'Agent'), ('technicien', 'Technicien'), ('restaurant', 'Restauration'), ('boutique', 'Bar & Boutique'), ('securite', 'Sécurité'), ('medical', 'Médical'), ('hse', 'HSE / QHSE'), ('accueil', "Agent d'accueil"), ('manager', 'Manager / Responsable')], default='agent', max_length=20),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='profil',
            field=models.CharField(blank=True, choices=[('admin', 'Administrateur'), ('agent', 'Agent'), ('technicien', 'Technicien'), ('restaurant', 'Restauration'), ('boutique', 'Bar & Boutique'), ('securite', 'Sécurité'), ('medical', 'Médical'), ('hse', 'HSE / QHSE'), ('accueil', "Agent d'accueil"), ('manager', 'Manager / Responsable')], default='agent', max_length=20),
        ),
    ]
