# Generated by Django 4.2.30 on 2026-09-05 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('residences', '0008_inductioncampconfig_inductioninfra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointInteret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('restaurant', '🍽️ Restaurant'), ('bar', '🍺 Bar & Boutique'), ('sport', '🏋️ Salle de sport'), ('rampe', '🚁 Rampe / Héliport'), ('securite', '🛡️ Sécurité'), ('infirmerie', '⚕️ Infirmerie'), ('parking', '🅿️ Parking'), ('bureau', '🏢 Bureau / Administration'), ('loisirs', '🎮 Loisirs'), ('autre', '📍 Autre')], default='autre', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True, default='')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Point d'intérêt",
                'ordering': ['categorie', 'nom'],
            },
        ),
    ]
