# Generated by Django 4.2.30 on 2026-09-05 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('residences', '0009_pointinteret'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheminCirculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, default='', max_length=100)),
                ('type_chemin', models.CharField(choices=[('rampe', '🛤️ Rampe'), ('galerie', '🏛️ Galerie couverte'), ('dallette', '🧱 Dallettes / passerelle au sol'), ('escalier', '🪜 Escalier'), ('chemin', '🚶 Chemin praticable'), ('autre', '➰ Autre')], default='chemin', max_length=20)),
                ('points', models.JSONField()),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chemin de circulation',
                'ordering': ['type_chemin', 'nom'],
            },
        ),
    ]
