# Generated by Django 4.2.30 on 2026-09-06 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('residences', '0010_chemincirculation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipementEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_epi', models.CharField(choices=[('casque', '⛑️ Casque'), ('chaussures', '🥾 Chaussures de sécurité'), ('gilet', '🦺 Gilet haute visibilité'), ('gants', '🧤 Gants'), ('lunettes', '🥽 Lunettes de protection'), ('auditive', '🎧 Protection auditive'), ('harnais', '🪢 Harnais'), ('masque', '😷 Masque'), ('autre', '📦 Autre')], max_length=20)),
                ('date_remise', models.DateField()),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('etat', models.CharField(choices=[('bon', 'Bon état'), ('use', 'Usé'), ('a_remplacer', 'À remplacer')], default='bon', max_length=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements_epi', to='residences.personnel')),
            ],
            options={
                'verbose_name': 'Équipement EPI',
                'ordering': ['date_expiration'],
            },
        ),
    ]
