# Generated by Django 4.2.30 on 2026-09-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0011_equipementepi'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonnel',
            name='est_expatrie',
            field=models.BooleanField(default=False, help_text="Personnel expatrié — nécessite des billets d'avion pour les rotations pays d'origine <-> mine"),
        ),
        migrations.AddField(
            model_name='historicalpersonnel',
            name='pays_origine',
            field=models.CharField(blank=True, default='', help_text="Pays d'origine — point de départ des billets d'avion pour le personnel expatrié", max_length=100),
        ),
        migrations.AddField(
            model_name='personnel',
            name='est_expatrie',
            field=models.BooleanField(default=False, help_text="Personnel expatrié — nécessite des billets d'avion pour les rotations pays d'origine <-> mine"),
        ),
        migrations.AddField(
            model_name='personnel',
            name='pays_origine',
            field=models.CharField(blank=True, default='', help_text="Pays d'origine — point de départ des billets d'avion pour le personnel expatrié", max_length=100),
        ),
    ]
