# Generated by Django 4.2.30 on 2026-09-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0012_historicalpersonnel_est_expatrie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonnel',
            name='eligible_mobilite',
            field=models.BooleanField(default=False, help_text="Droit d'utiliser le Centre de Mobilité (voyages/rotations) — automatique pour Roxgold et sous-traitants, doit être déclaré explicitement pour un visiteur même logé"),
        ),
        migrations.AddField(
            model_name='personnel',
            name='eligible_mobilite',
            field=models.BooleanField(default=False, help_text="Droit d'utiliser le Centre de Mobilité (voyages/rotations) — automatique pour Roxgold et sous-traitants, doit être déclaré explicitement pour un visiteur même logé"),
        ),
    ]
