# Generated by Django 4.2.30 on 2026-09-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0013_historicalpersonnel_eligible_mobilite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductioninfra',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='induction_infras/videos/'),
        ),
        migrations.AddField(
            model_name='inductioninfra',
            name='video_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
