# Generated by Django 4.2.30 on 2026-09-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0014_inductioninfra_video_inductioninfra_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batiment',
            name='statut',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Occupé', 'Occupé'), ('Réservé', 'Réservé'), ('Maintenance', 'Maintenance')], db_index=True, default='Libre', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalbatiment',
            name='statut',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Occupé', 'Occupé'), ('Réservé', 'Réservé'), ('Maintenance', 'Maintenance')], db_index=True, default='Libre', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalpersonnel',
            name='actif',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='actif',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
