# Generated by Django 4.2.30 on 2026-09-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0015_alter_batiment_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductionrecord',
            name='motif_refus',
            field=models.TextField(blank=True, default=''),
        ),
    ]
