# Generated by Django 4.2.30 on 2026-09-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0016_inductionrecord_motif_refus'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonnel',
            name='departement',
            field=models.CharField(blank=True, default='', help_text='Département/service au sein de la société (ex: Maintenance, RH, Logistique) — distinct de la société elle-même', max_length=100),
        ),
        migrations.AddField(
            model_name='personnel',
            name='departement',
            field=models.CharField(blank=True, default='', help_text='Département/service au sein de la société (ex: Maintenance, RH, Logistique) — distinct de la société elle-même', max_length=100),
        ),
    ]
