# Generated by Django 4.2.30 on 2026-09-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0017_historicalpersonnel_departement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpersonnel',
            name='profil',
            field=models.CharField(blank=True, default='agent', help_text="Profil metier libre, aligne sur les roles configures dans Parametrage -> Roles & Acces (RoleCustom) - PROFIL_CHOICES ci-dessus garde a titre de reference/valeurs par defaut, mais n'est plus applique comme contrainte stricte : un role personnalise cree par l'admin doit pouvoir etre assigne ici sans etre rejete.", max_length=30),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='profil',
            field=models.CharField(blank=True, default='agent', help_text="Profil metier libre, aligne sur les roles configures dans Parametrage -> Roles & Acces (RoleCustom) - PROFIL_CHOICES ci-dessus garde a titre de reference/valeurs par defaut, mais n'est plus applique comme contrainte stricte : un role personnalise cree par l'admin doit pouvoir etre assigne ici sans etre rejete.", max_length=30),
        ),
    ]
