# Generated by Django 4.2.30 on 2026-09-24 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('residences', '0018_alter_historicalpersonnel_profil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, help_text='NULL = toujours actif. Renseigne uniquement quand ce mandat de residence principale se termine (changement de chambre, fin de residence).', null=True)),
                ('motif_fin', models.CharField(blank=True, default='', max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('affecte_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residences_principales_affectees', to=settings.AUTH_USER_MODEL)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residents_principaux', to='residences.batiment')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residences_principales', to='residences.personnel')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalResidentPrincipal',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, help_text='NULL = toujours actif. Renseigne uniquement quand ce mandat de residence principale se termine (changement de chambre, fin de residence).', null=True)),
                ('motif_fin', models.CharField(blank=True, default='', max_length=200)),
                ('date_creation', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('affecte_par', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('batiment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='residences.batiment')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('personnel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='residences.personnel')),
            ],
            options={
                'verbose_name': 'historical resident principal',
                'verbose_name_plural': 'historical resident principals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
