# Generated by Django 4.2.30 on 2026-09-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residences", "0021_ajout_batiment_b187_204e"),
    ]

    operations = [
        migrations.AddField(
            model_name="chemincirculation",
            name="source_ref",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="pointinteret",
            name="geojson_geometry",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pointinteret",
            name="source_ref",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="chemincirculation",
            name="type_chemin",
            field=models.CharField(
                choices=[
                    ("rampe", "🛤️ Rampe"),
                    ("galerie", "🏛️ Galerie couverte"),
                    ("dallette", "🧱 Dallettes / passerelle au sol"),
                    ("escalier", "🪜 Escalier"),
                    ("chemin", "🚶 Chemin praticable"),
                    ("passerelle", "🌉 Passerelle"),
                    ("voirie", "🛣️ Voirie"),
                    ("talus", "⛰️ Talus en pierre"),
                    ("cloture", "🚧 Clôture"),
                    ("autre", "➰ Autre"),
                ],
                default="chemin",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pointinteret",
            name="categorie",
            field=models.CharField(
                choices=[
                    ("restaurant", "🍽️ Restaurant"),
                    ("bar", "🍺 Bar & Boutique"),
                    ("sport", "🏋️ Salle de sport"),
                    ("terrain_sport", "🏟️ Terrain de sport"),
                    ("rampe", "🚁 Rampe / Héliport"),
                    ("securite", "🛡️ Sécurité"),
                    ("guerite", "💂 Guérite"),
                    ("infirmerie", "⚕️ Infirmerie"),
                    ("parking", "🅿️ Parking"),
                    ("bureau", "🏢 Bureau / Administration"),
                    ("communautaire", "🏢 Bureau communautaire"),
                    ("accueil", "🛎️ Bureau d'accueil"),
                    ("reunion", "🗣️ Salle de réunion"),
                    ("serveur", "🖥️ Salle serveur"),
                    ("ats", "🏢 Bureau ATS"),
                    ("toilette", "🚽 Toilette"),
                    ("toilette_commune", "🚻 Toilette commune"),
                    ("loisirs", "🎮 Loisirs"),
                    ("autre", "📍 Autre"),
                ],
                default="autre",
                max_length=20,
            ),
        ),
    ]
