# Generated by Django 4.2.30 on 2026-09-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residences", "0022_chemincirculation_source_ref_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlainteCategorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50, unique=True)),
                (
                    "sous_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste de sous-categories (texte libre), ex: ['sol','plafond','autre']",
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                ("ordre", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Catégorie de plainte",
                "verbose_name_plural": "Catégories de plainte",
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.AlterField(
            model_name="historicalplainte",
            name="categorie",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="plainte",
            name="categorie",
            field=models.CharField(max_length=30),
        ),
    ]
