# Generated by Django 4.2.30 on 2026-10-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residences", "0025_import_chambre_b106"),
    ]

    operations = [
        migrations.AddField(
            model_name="batiment",
            name="etage",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalbatiment",
            name="etage",
            field=models.IntegerField(default=0),
        ),
    ]
