# Generated by Django 4.2.30 on 2026-10-09 11:46

from django.db import migrations, models
import django.db.models.deletion


DEPARTEMENTS = ["Mining", "Procurement", "Process", "IT", "Site Admin", "Finance", "Security", "OHS / ERT",
                "Developpement durable", "HR", "Projects", "Mobile Maintenance", "Exploration"]
# (entreprise, département Roxgold | None, entreprise mère | None) — d'après « Camp Occupancy » (fichier d'exemple)
ENTREPRISES = [
    ("MOTA ENGIL", "Mining", None), ("DESIMONE", "Mining", None), ("ICS (Ivory Coast Services)", "Mining", None),
    ("DGMG / DR MINES", "Mining", None),
    ("JACHRIS", None, "MOTA ENGIL"), ("NEEMBA", None, "MOTA ENGIL"), ("MAXAM", None, "MOTA ENGIL"), ("BIA", None, "MOTA ENGIL"),
    ("ATS", "Site Admin", None), ("MEDICIS", "OHS / ERT", None), ("TOTAL ENERGIES", "Procurement", None),
    ("KNIGHT PIESOLD", "Projects", None), ("SGS", "Process", None), ("ALTAAQA GLOBAL", "Process", None),
    ("SOVENTIX", "Projects", None), ("BUREAU VERITAS", "Projects", None), ("TOTAL SOLAR PV", "Projects", None),
]


def semer(apps, schema_editor):
    Departement = apps.get_model("residences", "Departement")
    Entreprise = apps.get_model("residences", "Entreprise")
    for i, nom in enumerate(DEPARTEMENTS, 1):
        Departement.objects.get_or_create(nom=nom, defaults={"ordre": i})
    for nom, dep, mere in ENTREPRISES:
        if mere:
            continue
        Entreprise.objects.get_or_create(nom=nom, defaults={"departement": Departement.objects.get(nom=dep)})
    for nom, dep, mere in ENTREPRISES:
        if mere:
            Entreprise.objects.get_or_create(nom=nom, defaults={"entreprise_mere": Entreprise.objects.get(nom=mere)})


class Migration(migrations.Migration):

    dependencies = [
        ("residences", "0026_batiment_etage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Departement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Entreprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("actif", models.BooleanField(default=True)),
                (
                    "departement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entreprises",
                        to="residences.departement",
                    ),
                ),
                (
                    "entreprise_mere",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sous_traitants",
                        to="residences.entreprise",
                    ),
                ),
            ],
            options={
                "ordering": ["nom"],
            },
        ),
        migrations.RunPython(semer, migrations.RunPython.noop),
    ]
