# Generated by Django 4.2.30 on 2026-10-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residences", "0027_departements_entreprises"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpersonnel",
            name="mobilite_exclue",
            field=models.BooleanField(
                default=False,
                help_text="Roxgold/sous-traitant à qui on a RETIRÉ le droit au Centre de Mobilité (par défaut ils l'ont)",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="mobilite_exclue",
            field=models.BooleanField(
                default=False,
                help_text="Roxgold/sous-traitant à qui on a RETIRÉ le droit au Centre de Mobilité (par défaut ils l'ont)",
            ),
        ),
    ]
