# Generated by Django 6.0.5 on 2026-05-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauration', '0006_add_bon_caisse'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type_plat', models.CharField(choices=[('entree', 'Entrée'), ('plat', 'Plat principal'), ('dessert', 'Dessert'), ('boisson', 'Boisson'), ('special', 'Plat spécial')], default='plat', max_length=20)),
                ('date_service', models.DateField()),
                ('repas', models.CharField(choices=[('matin', 'Petit déjeuner'), ('midi', 'Déjeuner'), ('soir', 'Dîner')], default='midi', max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Menu du jour',
                'ordering': ['date_service', 'repas', 'type_plat'],
            },
        ),
    ]
