# Generated by Django 6.0.5 on 2026-05-08 22:58

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residences', '0004_alter_batiment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteCampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type_alerte', models.CharField(choices=[('info', 'Info'), ('warning', 'Attention'), ('danger', 'Urgent'), ('success', 'OK')], default='info', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_event', models.CharField(choices=[('reunion', 'Réunion'), ('securite', 'Sécurité'), ('formation', 'Formation'), ('social', 'Social / Loisir'), ('sport', 'Sport'), ('alerte', 'Alerte'), ('maintenance', 'Maintenance campus'), ('autre', 'Autre')], default='reunion', max_length=30)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('image_base64', models.TextField(blank=True, default='')),
                ('obligatoire', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evenement',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEvenement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_event', models.CharField(choices=[('reunion', 'Réunion'), ('securite', 'Sécurité'), ('formation', 'Formation'), ('social', 'Social / Loisir'), ('sport', 'Sport'), ('alerte', 'Alerte'), ('maintenance', 'Maintenance campus'), ('autre', 'Autre')], default='reunion', max_length=30)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('image_base64', models.TextField(blank=True, default='')),
                ('obligatoire', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cree_par', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Evenement',
                'verbose_name_plural': 'historical Evenements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lu', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('envoye_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='evenements.evenement')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='residences.personnel')),
            ],
            options={
                'ordering': ['-date_envoi'],
                'unique_together': {('evenement', 'personnel')},
            },
        ),
    ]
