# Generated by Django 4.2.30 on 2026-09-20 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0018_alter_historicalpersonnel_profil_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evenements', '0002_simplenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='propose_boisson',
            field=models.BooleanField(default=False, help_text="Proposer un choix alcool/sucrerie a la generation du QR de chaque personne, pour la logistique de l'evenement"),
        ),
        migrations.AddField(
            model_name='evenement',
            name='qr_requis',
            field=models.BooleanField(default=False, help_text="Genere un QR individuel a usage unique par personne pour l'acces a cet evenement (ex: barbecue) - une fois scanne, le code ne peut plus etre reutilise"),
        ),
        migrations.AddField(
            model_name='historicalevenement',
            name='propose_boisson',
            field=models.BooleanField(default=False, help_text="Proposer un choix alcool/sucrerie a la generation du QR de chaque personne, pour la logistique de l'evenement"),
        ),
        migrations.AddField(
            model_name='historicalevenement',
            name='qr_requis',
            field=models.BooleanField(default=False, help_text="Genere un QR individuel a usage unique par personne pour l'acces a cet evenement (ex: barbecue) - une fois scanne, le code ne peut plus etre reutilise"),
        ),
        migrations.CreateModel(
            name='QREvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('preference_boisson', models.CharField(blank=True, choices=[('alcool', '🍺 Alcool'), ('sucrerie', '🥤 Sucrerie / Sans alcool')], default='', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('utilise', models.BooleanField(default=False)),
                ('utilise_le', models.DateTimeField(blank=True, null=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='evenements.evenement')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_evenements', to='residences.personnel')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_evenements_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
                'unique_together': {('evenement', 'personnel')},
            },
        ),
    ]
