# Generated by Django 4.2.30 on 2026-09-21 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0003_evenement_propose_boisson_evenement_qr_requis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeDiffusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('uniquement_residents_actifs', models.BooleanField(default=False, help_text='Seulement le personnel actuellement loge dans une chambre occupee')),
                ('filtre_societe', models.CharField(blank=True, default='', help_text='Ex: ROXGOLD - vide = toutes societes', max_length=100)),
                ('filtre_type_personnel', models.CharField(blank=True, default='', help_text='Ex: roxgold, sous_traitant, visiteur - vide = tous types', max_length=30)),
                ('est_defaut', models.BooleanField(default=False, help_text="Pre-selectionne a la creation d'un nouvel evenement")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='evenement',
            name='groupe_diffusion',
            field=models.ForeignKey(blank=True, help_text='Qui recoit la notification - configure dans Parametrage. Vide = comportement historique (residents actifs uniquement)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to='evenements.groupediffusion'),
        ),
        migrations.AddField(
            model_name='historicalevenement',
            name='groupe_diffusion',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Qui recoit la notification - configure dans Parametrage. Vide = comportement historique (residents actifs uniquement)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='evenements.groupediffusion'),
        ),
    ]
