# Generated by Django 4.2.30 on 2026-10-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evenements", "0005_bootstrap_groupes_diffusion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrevenement",
            name="preference_boisson",
            field=models.CharField(
                blank=True,
                choices=[
                    ("alcool", "🍺 Alcool"),
                    ("sucrerie", "🥤 Sucrerie / Sans alcool"),
                    ("alcool_sucrerie", "🍺🥤 Alcool + Sucrerie"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
