# Generated by Django 4.2.30 on 2026-09-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0002_historicalvoyage_heure_depart_voyage_heure_depart'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvoyage',
            name='nb_places_total',
            field=models.PositiveIntegerField(blank=True, default=15, help_text='Capacité totale du véhicule pour ce convoi', null=True),
        ),
        migrations.AddField(
            model_name='historicalvoyage',
            name='notes_admin',
            field=models.TextField(blank=True, help_text='Notes internes admin'),
        ),
        migrations.AddField(
            model_name='historicalvoyage',
            name='point_rdv',
            field=models.CharField(blank=True, help_text='Point de rendez-vous / embarquement', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalvoyage',
            name='rotation_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID partagé entre tous les voyageurs du même convoi', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalvoyage',
            name='type_voyage',
            field=models.CharField(blank=True, choices=[('individuel', 'Individuel'), ('rotation', 'Rotation groupe'), ('urgence', 'Urgence'), ('medical', 'Médical')], default='individuel', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalvoyage',
            name='vehicule',
            field=models.CharField(blank=True, help_text='BUS-01, 4WD-02, VOL-AIR...', max_length=50),
        ),
        migrations.AddField(
            model_name='voyage',
            name='nb_places_total',
            field=models.PositiveIntegerField(blank=True, default=15, help_text='Capacité totale du véhicule pour ce convoi', null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='notes_admin',
            field=models.TextField(blank=True, help_text='Notes internes admin'),
        ),
        migrations.AddField(
            model_name='voyage',
            name='point_rdv',
            field=models.CharField(blank=True, help_text='Point de rendez-vous / embarquement', max_length=200),
        ),
        migrations.AddField(
            model_name='voyage',
            name='rotation_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID partagé entre tous les voyageurs du même convoi', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='type_voyage',
            field=models.CharField(blank=True, choices=[('individuel', 'Individuel'), ('rotation', 'Rotation groupe'), ('urgence', 'Urgence'), ('medical', 'Médical')], default='individuel', max_length=20),
        ),
        migrations.AddField(
            model_name='voyage',
            name='vehicule',
            field=models.CharField(blank=True, help_text='BUS-01, 4WD-02, VOL-AIR...', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalvoyage',
            name='heure_depart',
            field=models.TimeField(blank=True, help_text='Heure de départ prévue', null=True),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='heure_depart',
            field=models.TimeField(blank=True, help_text='Heure de départ prévue', null=True),
        ),
    ]
