# Generated by Django 4.2.30 on 2026-09-12 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voyages', '0003_historicalvoyage_nb_places_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvoyage',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalvoyage',
            name='motif_refus',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicalvoyage',
            name='statut_validation',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=15),
        ),
        migrations.AddField(
            model_name='historicalvoyage',
            name='valide_par',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voyage',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='motif_refus',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='voyage',
            name='statut_validation',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=15),
        ),
        migrations.AddField(
            model_name='voyage',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voyages_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EtapeVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('origine', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('mode_transport', models.CharField(choices=[('bus', '🚌 Bus'), ('4x4', '🚙 4x4 / Véhicule tout-terrain'), ('avion', '✈️ Avion'), ('bateau', '⛴️ Bateau'), ('a_pied', '🚶 À pied'), ('autre', '🚐 Autre')], default='bus', max_length=15)),
                ('date_etape', models.DateField()),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('heure_arrivee_prevue', models.TimeField(blank=True, null=True)),
                ('point_rdv', models.CharField(blank=True, default='', max_length=200)),
                ('reference', models.CharField(blank=True, default='', help_text='Numéro de vol, plaque du véhicule, référence de réservation...', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='voyages.voyage')),
            ],
            options={
                'verbose_name': 'Étape de voyage',
                'ordering': ['voyage', 'ordre'],
            },
        ),
    ]
