# Generated by Django 4.2.30 on 2026-09-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0004_historicalvoyage_date_validation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvoyage',
            name='origine',
            field=models.CharField(blank=True, default='Camp Roxgold Sango', help_text="Point de départ réel — pas toujours le camp (ex: premier voyage d'un nouvel employé, qui part de chez lui VERS le camp)", max_length=200),
        ),
        migrations.AddField(
            model_name='voyage',
            name='origine',
            field=models.CharField(blank=True, default='Camp Roxgold Sango', help_text="Point de départ réel — pas toujours le camp (ex: premier voyage d'un nouvel employé, qui part de chez lui VERS le camp)", max_length=200),
        ),
    ]
