# Generated by Django 4.2.30 on 2026-09-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0005_historicalvoyage_origine_voyage_origine'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvoyage',
            name='vehicule_matricule',
            field=models.CharField(blank=True, default='', help_text="Plaque d'immatriculation — aide l'agent à repérer le bon véhicule au parking", max_length=30),
        ),
        migrations.AddField(
            model_name='historicalvoyage',
            name='vehicule_photo',
            field=models.TextField(blank=True, default='', help_text='Photo du véhicule en base64 — usage exceptionnel, pour reconnaissance visuelle rapide au parking'),
        ),
        migrations.AddField(
            model_name='voyage',
            name='vehicule_matricule',
            field=models.CharField(blank=True, default='', help_text="Plaque d'immatriculation — aide l'agent à repérer le bon véhicule au parking", max_length=30),
        ),
        migrations.AddField(
            model_name='voyage',
            name='vehicule_photo',
            field=models.TextField(blank=True, default='', help_text='Photo du véhicule en base64 — usage exceptionnel, pour reconnaissance visuelle rapide au parking'),
        ),
    ]
