# Generated by Django 4.2.30 on 2026-09-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0006_historicalvoyage_vehicule_matricule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculeFlotte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('4x4', '🚙 4x4'), ('pickup', '🛻 Pick-up'), ('minibus', '🚐 Minibus'), ('bus', '🚌 Bus'), ('avion', '✈️ Avion'), ('autre', '🚗 Autre')], default='4x4', max_length=15)),
                ('matricule', models.CharField(blank=True, default='', max_length=30)),
                ('capacite', models.PositiveIntegerField(default=7)),
                ('photo', models.TextField(blank=True, default='')),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Véhicule de la flotte',
                'ordering': ['categorie', 'nom'],
            },
        ),
    ]
