# Generated by Django 4.2.30 on 2026-09-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0008_seed_vehicules_flotte'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvoyage',
            name='conducteur',
            field=models.CharField(blank=True, default='', help_text='Nom du conducteur assigné pour ce voyage — change trop souvent pour être lié au véhicule lui-même', max_length=100),
        ),
        migrations.AddField(
            model_name='voyage',
            name='conducteur',
            field=models.CharField(blank=True, default='', help_text='Nom du conducteur assigné pour ce voyage — change trop souvent pour être lié au véhicule lui-même', max_length=100),
        ),
    ]
