# Generated by Django 4.2.30 on 2026-09-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0009_historicalvoyage_conducteur_voyage_conducteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvoyage',
            name='conducteur_retour',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalvoyage',
            name='vehicule_matricule_retour',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='historicalvoyage',
            name='vehicule_retour',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='voyage',
            name='conducteur_retour',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='voyage',
            name='vehicule_matricule_retour',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='voyage',
            name='vehicule_retour',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalvoyage',
            name='conducteur',
            field=models.CharField(blank=True, default='', help_text="Nom du conducteur assigné pour l'ALLER — change trop souvent pour être lié au véhicule lui-même", max_length=100),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='conducteur',
            field=models.CharField(blank=True, default='', help_text="Nom du conducteur assigné pour l'ALLER — change trop souvent pour être lié au véhicule lui-même", max_length=100),
        ),
    ]
