# Generated by Django 4.2.30 on 2026-09-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0010_historicalvoyage_conducteur_retour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapevoyage',
            name='billet_cout',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Coût du billet — pour le suivi budgétaire du personnel expatrié', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='etapevoyage',
            name='billet_fichier',
            field=models.TextField(blank=True, default='', help_text="Scan/PDF du billet d'avion en base64 — justificatif pour la comptabilité"),
        ),
    ]
