# Generated by Django 4.2.30 on 2026-09-13 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0011_etapevoyage_billet_cout_etapevoyage_billet_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapevoyage',
            name='conducteur',
            field=models.CharField(blank=True, default='', help_text='Conducteur assigne pour cette etape specifique', max_length=100),
        ),
        migrations.AddField(
            model_name='etapevoyage',
            name='sens',
            field=models.CharField(choices=[('aller', '➡️ Aller'), ('retour', '⬅️ Retour'), ('interne', '🔁 Trajet interne')], default='aller', help_text='Aller ou retour — vehicule/conducteur/equipage peuvent differer entre les deux', max_length=10),
        ),
        migrations.AddField(
            model_name='etapevoyage',
            name='vehicule_flotte',
            field=models.ForeignKey(blank=True, help_text='Vehicule du catalogue partage - matricule/photo herites automatiquement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapes', to='voyages.vehiculeflotte'),
        ),
    ]
