# Generated by Django 4.2.30 on 2026-09-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0012_etapevoyage_conducteur_etapevoyage_sens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculeflotte',
            name='categorie',
            field=models.CharField(choices=[('4x4', '🚙 4x4'), ('pickup', '🛻 Pick-up'), ('minibus', '🚐 Minibus'), ('bus', '🚌 Bus'), ('avion', '✈️ Avion'), ('bateau', '⛴️ Bateau'), ('autre', '🚗 Autre')], default='4x4', max_length=15),
        ),
    ]
