# Generated by Django 4.2.30 on 2026-09-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0018_corriger_capacites_vehicule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvoyage',
            name='statut',
            field=models.CharField(choices=[('planifie', 'Planifié'), ('en_voyage', 'En voyage'), ('retour', 'Retour au camp'), ('annule', 'Annulé')], db_index=True, default='planifie', max_length=20),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='statut',
            field=models.CharField(choices=[('planifie', 'Planifié'), ('en_voyage', 'En voyage'), ('retour', 'Retour au camp'), ('annule', 'Annulé')], db_index=True, default='planifie', max_length=20),
        ),
    ]
