# Generated by Django 4.2.30 on 2026-09-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0019_alter_historicalvoyage_statut_alter_voyage_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvoyage',
            name='date_depart_effective',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='date_depart_effective',
            field=models.DateField(blank=True, null=True),
        ),
    ]
