# Generated by Django 4.2.30 on 2026-09-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0020_historicalvoyage_date_depart_effective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvoyage',
            name='conducteur_secondaire',
            field=models.CharField(blank=True, default='', help_text='Second chauffeur / chauffeur de relève pour ce trajet (long trajet, sécurité) — distinct du conducteur du retour', max_length=100),
        ),
        migrations.AddField(
            model_name='voyage',
            name='conducteur_secondaire',
            field=models.CharField(blank=True, default='', help_text='Second chauffeur / chauffeur de relève pour ce trajet (long trajet, sécurité) — distinct du conducteur du retour', max_length=100),
        ),
    ]
