# Generated by Django 4.2.30 on 2026-09-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0021_historicalvoyage_conducteur_secondaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvoyage',
            name='lieu_descente_retour',
            field=models.CharField(blank=True, default='', help_text="Où CE passager descend precisement pour le RETOUR, si different (ex: depose avant l'arrivee finale du convoi) — vide = destination normale (origine)", max_length=200),
        ),
        migrations.AddField(
            model_name='historicalvoyage',
            name='lieu_montee_retour',
            field=models.CharField(blank=True, default='', help_text='Où CE passager monte precisement pour le RETOUR, si different du reste du convoi (ex: recupere en cours de route) — vide = meme point que le convoi', max_length=200),
        ),
        migrations.AddField(
            model_name='voyage',
            name='lieu_descente_retour',
            field=models.CharField(blank=True, default='', help_text="Où CE passager descend precisement pour le RETOUR, si different (ex: depose avant l'arrivee finale du convoi) — vide = destination normale (origine)", max_length=200),
        ),
        migrations.AddField(
            model_name='voyage',
            name='lieu_montee_retour',
            field=models.CharField(blank=True, default='', help_text='Où CE passager monte precisement pour le RETOUR, si different du reste du convoi (ex: recupere en cours de route) — vide = meme point que le convoi', max_length=200),
        ),
    ]
