# Generated by Django 4.2.30 on 2026-09-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0022_historicalvoyage_lieu_descente_retour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapevoyage',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Distance approximative de cette étape en km — pour le plan de gestion de voyage (JMP)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='etapevoyage',
            name='pause_fatigue',
            field=models.CharField(blank=True, default='', help_text="Gestion de la fatigue du conducteur à cette étape (ex: '15 MIN DE PAUSE', 'N/A') — pour le JMP", max_length=50),
        ),
        migrations.AddField(
            model_name='historicalvoyage',
            name='niveau_alerte',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Aucune restriction de voyage'), (2, 'Prudence — coordination entre CCTV'), (3, 'Minimum de 2 convois de véhicules'), (4, 'Escorte gendarme/policière requise'), (5, "Aucun voyage n'est autorisé")], default=1, help_text="Niveau d'alerte sécurité sur l'itinéraire — pour le plan de gestion de voyage (JMP)"),
        ),
        migrations.AddField(
            model_name='voyage',
            name='niveau_alerte',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Aucune restriction de voyage'), (2, 'Prudence — coordination entre CCTV'), (3, 'Minimum de 2 convois de véhicules'), (4, 'Escorte gendarme/policière requise'), (5, "Aucun voyage n'est autorisé")], default=1, help_text="Niveau d'alerte sécurité sur l'itinéraire — pour le plan de gestion de voyage (JMP)"),
        ),
    ]
