# Generated by Django 4.2.30 on 2026-09-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0023_etapevoyage_distance_km_etapevoyage_pause_fatigue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvoyage',
            name='trajet_aller_seul',
            field=models.BooleanField(default=False, help_text="Rotation = un trajet aller a travers plusieurs villes intermediaires, PAS un aller-retour couple. Un eventuel retour doit etre cree comme une NOUVELLE rotation separee, independante. Quand actif, la fin du trajet ne tente jamais de restituer une chambre au camp (la destination n'est pas forcement le camp)."),
        ),
        migrations.AddField(
            model_name='voyage',
            name='trajet_aller_seul',
            field=models.BooleanField(default=False, help_text="Rotation = un trajet aller a travers plusieurs villes intermediaires, PAS un aller-retour couple. Un eventuel retour doit etre cree comme une NOUVELLE rotation separee, independante. Quand actif, la fin du trajet ne tente jamais de restituer une chambre au camp (la destination n'est pas forcement le camp)."),
        ),
    ]
