# Generated by Django 4.2.30 on 2026-09-26 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0019_residentprincipal_historicalresidentprincipal'),
        ('voyages', '0024_historicalvoyage_trajet_aller_seul_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvoyage',
            name='conducteur_personnel',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Référence réelle vers le personnel désigné conducteur — le champ 'conducteur' (texte) reste rempli en parallèle pour l'affichage (JMP, historique) et la compatibilité avec le code existant, mais cette FK est désormais la source de vérité pour les contrôles d'intégrité (une personne ne peut pas être conducteur ET passager).", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='residences.personnel'),
        ),
        migrations.AddField(
            model_name='historicalvoyage',
            name='conducteur_secondaire_personnel',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Voir conducteur_personnel — même principe pour le second chauffeur.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='residences.personnel'),
        ),
        migrations.AddField(
            model_name='voyage',
            name='conducteur_personnel',
            field=models.ForeignKey(blank=True, help_text="Référence réelle vers le personnel désigné conducteur — le champ 'conducteur' (texte) reste rempli en parallèle pour l'affichage (JMP, historique) et la compatibilité avec le code existant, mais cette FK est désormais la source de vérité pour les contrôles d'intégrité (une personne ne peut pas être conducteur ET passager).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voyages_comme_conducteur', to='residences.personnel'),
        ),
        migrations.AddField(
            model_name='voyage',
            name='conducteur_secondaire_personnel',
            field=models.ForeignKey(blank=True, help_text='Voir conducteur_personnel — même principe pour le second chauffeur.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voyages_comme_conducteur_secondaire', to='residences.personnel'),
        ),
    ]
