# Generated by Django 4.2.30 on 2026-09-26 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('residences', '0019_residentprincipal_historicalresidentprincipal'),
        ('voyages', '0026_relier_conducteurs_existants'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvoyage',
            name='demande_origine',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Demande de voyage a l'origine de ce voyage, si cree depuis une demande validee (refonte Centre de Mobilite) - trace le lien demande -> rotation sans dupliquer le systeme de demandes existant.", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='residences.demande'),
        ),
        migrations.AddField(
            model_name='voyage',
            name='demande_origine',
            field=models.ForeignKey(blank=True, help_text="Demande de voyage a l'origine de ce voyage, si cree depuis une demande validee (refonte Centre de Mobilite) - trace le lien demande -> rotation sans dupliquer le systeme de demandes existant.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voyages_generes', to='residences.demande'),
        ),
        migrations.CreateModel(
            name='EvenementMonteeDescente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evenement', models.CharField(choices=[('montee', '🟢 Montée'), ('descente', '🔴 Descente')], max_length=10)),
                ('lieu', models.CharField(max_length=150)),
                ('date_heure', models.DateTimeField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements_montee_descente', to='voyages.voyage')),
            ],
            options={
                'verbose_name': 'Événement montée/descente',
                'ordering': ['voyage', 'date_heure'],
            },
        ),
    ]
