# Generated by Django 4.2.30 on 2026-09-26 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0019_residentprincipal_historicalresidentprincipal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voyages', '0027_historicalvoyage_demande_origine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotation_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('vehicule', models.CharField(blank=True, default='', max_length=100)),
                ('vehicule_matricule', models.CharField(blank=True, default='', max_length=30)),
                ('vehicule_photo', models.TextField(blank=True, default='')),
                ('conducteur', models.CharField(blank=True, default='', max_length=100)),
                ('conducteur_secondaire', models.CharField(blank=True, default='', max_length=100)),
                ('destination', models.CharField(blank=True, default='', max_length=200)),
                ('origine', models.CharField(blank=True, default='', max_length=200)),
                ('date_depart', models.DateField()),
                ('date_retour_prevue', models.DateField()),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('point_rdv', models.CharField(blank=True, default='', max_length=200)),
                ('motif', models.CharField(blank=True, default='', max_length=200)),
                ('nb_places_total', models.PositiveIntegerField(default=15)),
                ('niveau_alerte', models.PositiveSmallIntegerField(default=1)),
                ('trajet_aller_seul', models.BooleanField(default=False)),
                ('statut', models.CharField(default='planifie', help_text="Statut de la rotation elle-meme (independant du statut de chaque Voyage individuel) - utile tant qu'aucun passager n'est encore assigne.", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conducteur_personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotations_conduites', to='residences.personnel')),
                ('conducteur_secondaire_personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotations_conduites_second', to='residences.personnel')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalRotation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('rotation_id', models.CharField(db_index=True, max_length=20)),
                ('vehicule', models.CharField(blank=True, default='', max_length=100)),
                ('vehicule_matricule', models.CharField(blank=True, default='', max_length=30)),
                ('vehicule_photo', models.TextField(blank=True, default='')),
                ('conducteur', models.CharField(blank=True, default='', max_length=100)),
                ('conducteur_secondaire', models.CharField(blank=True, default='', max_length=100)),
                ('destination', models.CharField(blank=True, default='', max_length=200)),
                ('origine', models.CharField(blank=True, default='', max_length=200)),
                ('date_depart', models.DateField()),
                ('date_retour_prevue', models.DateField()),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('point_rdv', models.CharField(blank=True, default='', max_length=200)),
                ('motif', models.CharField(blank=True, default='', max_length=200)),
                ('nb_places_total', models.PositiveIntegerField(default=15)),
                ('niveau_alerte', models.PositiveSmallIntegerField(default=1)),
                ('trajet_aller_seul', models.BooleanField(default=False)),
                ('statut', models.CharField(default='planifie', help_text="Statut de la rotation elle-meme (independant du statut de chaque Voyage individuel) - utile tant qu'aucun passager n'est encore assigne.", max_length=20)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('conducteur_personnel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='residences.personnel')),
                ('conducteur_secondaire_personnel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='residences.personnel')),
                ('enregistre_par', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical rotation',
                'verbose_name_plural': 'historical rotations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
