# Generated by Django 4.2.30 on 2026-09-28 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("voyages", "0029_backfill_rotations_existantes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItineraireModele",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(help_text="Ex: Camp → Abidjan", max_length=100),
                ),
                ("origine", models.CharField(max_length=200)),
                ("destination", models.CharField(max_length=200)),
                ("actif", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Itinéraire modèle",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="EtapeItineraireModele",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordre", models.PositiveIntegerField(default=1)),
                ("ville", models.CharField(max_length=150)),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                ("heure_depart", models.TimeField(blank=True, null=True)),
                ("heure_arrivee", models.TimeField(blank=True, null=True)),
                (
                    "pause_fatigue",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "itineraire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapes",
                        to="voyages.itinerairemodele",
                    ),
                ),
            ],
            options={
                "verbose_name": "Étape d'itinéraire modèle",
                "ordering": ["itineraire", "ordre"],
            },
        ),
    ]
