# Generated by Django 4.2.30 on 2026-09-28 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("voyages", "0031_bootstrap_itineraires_camp_abidjan"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrotation",
            name="itineraire_modele",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Itineraire type choisi a la creation du convoi (memoire meme sans aucun passager) - applique automatiquement aux etapes du voyage de CHAQUE passager qui rejoint ensuite ce convoi, tant que celui-ci n'a pas deja ses propres etapes.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="voyages.itinerairemodele",
            ),
        ),
        migrations.AddField(
            model_name="rotation",
            name="itineraire_modele",
            field=models.ForeignKey(
                blank=True,
                help_text="Itineraire type choisi a la creation du convoi (memoire meme sans aucun passager) - applique automatiquement aux etapes du voyage de CHAQUE passager qui rejoint ensuite ce convoi, tant que celui-ci n'a pas deja ses propres etapes.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rotations",
                to="voyages.itinerairemodele",
            ),
        ),
    ]
