# Generated by Django 4.2.30 on 2026-10-05 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("voyages", "0032_historicalrotation_itineraire_modele_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuiviConvoi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_route", "🚐 En route"),
                            ("arret", "⏸️ À l'arrêt"),
                            ("arrive", "🏁 Arrivé"),
                        ],
                        db_index=True,
                        default="en_route",
                        max_length=10,
                    ),
                ),
                ("depart_at", models.DateTimeField()),
                ("arrivee_at", models.DateTimeField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("vitesse_kmh", models.FloatField(blank=True, null=True)),
                (
                    "cap",
                    models.FloatField(
                        blank=True,
                        help_text="Direction en degrés (0 = nord)",
                        null=True,
                    ),
                ),
                ("position_at", models.DateTimeField(blank=True, null=True)),
                ("nb_passagers_depart", models.PositiveIntegerField(default=0)),
                (
                    "demarre_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rotation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suivi",
                        to="voyages.rotation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suivi de convoi",
            },
        ),
        migrations.CreateModel(
            name="PositionConvoi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("vitesse_kmh", models.FloatField(blank=True, null=True)),
                ("date_heure", models.DateTimeField(db_index=True)),
                (
                    "suivi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="voyages.suiviconvoi",
                    ),
                ),
            ],
            options={
                "ordering": ["suivi", "date_heure"],
            },
        ),
        migrations.CreateModel(
            name="ArretConvoi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_arret",
                    models.CharField(
                        choices=[
                            ("pause", "☕ Pause"),
                            ("depose", "⬇️ Dépose passagers"),
                            ("ramassage", "⬆️ Ramassage"),
                            ("controle", "🛂 Contrôle / barrage"),
                            ("carburant", "⛽ Carburant"),
                            ("incident", "⚠️ Incident / panne"),
                        ],
                        default="pause",
                        max_length=12,
                    ),
                ),
                ("lieu", models.CharField(blank=True, default="", max_length=150)),
                ("note", models.CharField(blank=True, default="", max_length=300)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("debut", models.DateTimeField()),
                ("fin", models.DateTimeField(blank=True, null=True)),
                (
                    "nb_a_bord",
                    models.PositiveIntegerField(
                        default=0, help_text="Passagers à bord APRÈS cet arrêt"
                    ),
                ),
                (
                    "suivi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrets",
                        to="voyages.suiviconvoi",
                    ),
                ),
            ],
            options={
                "ordering": ["suivi", "debut"],
            },
        ),
        migrations.CreateModel(
            name="DeposeArret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arret",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposes",
                        to="voyages.arretconvoi",
                    ),
                ),
                (
                    "voyage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposes_convoi",
                        to="voyages.voyage",
                    ),
                ),
            ],
            options={
                "unique_together": {("arret", "voyage")},
            },
        ),
    ]
