# Generated by Django 4.2.30 on 2026-10-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voyages", "0033_suivi_convoi_direct"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalvoyage",
            name="vehicule_personnel",
            field=models.BooleanField(
                default=False,
                help_text="Le voyageur part avec SON propre véhicule (résident qui fait ses rotations en voiture personnelle) : voyage individuel, jamais à organiser dans un convoi. L'immatriculation éventuelle est dans vehicule_matricule.",
            ),
        ),
        migrations.AddField(
            model_name="voyage",
            name="vehicule_personnel",
            field=models.BooleanField(
                default=False,
                help_text="Le voyageur part avec SON propre véhicule (résident qui fait ses rotations en voiture personnelle) : voyage individuel, jamais à organiser dans un convoi. L'immatriculation éventuelle est dans vehicule_matricule.",
            ),
        ),
    ]
