# Generated by Django 6.0.5 on 2026-05-26 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0005_demande_historicaldemande'),
    ]

    operations = [
        migrations.CreateModel(
            name='InductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé — Induit'), ('refuse', 'Refusé'), ('expire', 'Expiré')], default='en_cours', max_length=20)),
                ('etapes_data', models.JSONField(blank=True, default=dict)),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('docs_data', models.JSONField(blank=True, default=dict)),
                ('medical_data', models.JSONField(blank=True, default=dict)),
                ('quiz_score', models.PositiveIntegerField(blank=True, null=True)),
                ('quiz_tentatives', models.PositiveIntegerField(default=0)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('badge_emis', models.BooleanField(default=False)),
                ('badge_date', models.DateTimeField(blank=True, null=True)),
                ('badge_expire', models.DateField(blank=True, null=True)),
                ('personnel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='induction', to='residences.personnel')),
            ],
            options={
                'verbose_name': 'Induction QHSE',
                'ordering': ['-date_debut'],
            },
        ),
    ]
