# Generated by Django 6.0.5 on 2026-05-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0006_add_induction_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonnel',
            name='profil',
            field=models.CharField(blank=True, choices=[('admin', 'Administrateur'), ('agent', 'Agent'), ('technicien', 'Technicien'), ('restaurant', 'Restauration'), ('boutique', 'Bar & Boutique'), ('securite', 'Sécurité'), ('medical', 'Médical'), ('manager', 'Manager / Responsable')], default='agent', max_length=20),
        ),
        migrations.AddField(
            model_name='personnel',
            name='profil',
            field=models.CharField(blank=True, choices=[('admin', 'Administrateur'), ('agent', 'Agent'), ('technicien', 'Technicien'), ('restaurant', 'Restauration'), ('boutique', 'Bar & Boutique'), ('securite', 'Sécurité'), ('medical', 'Médical'), ('manager', 'Manager / Responsable')], default='agent', max_length=20),
        ),
    ]
