# Generated by Django 4.2.30 on 2026-05-18 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0003_remove_historicalincident_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalincident',
            name='commentaire_cloture',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='commentaire_resolution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='date_assignation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='date_cloture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='date_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='sla_depasse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='sla_echeance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='sla_notification_envoyee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='commentaire_cloture',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='commentaire_resolution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='date_assignation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='date_cloture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='date_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='sla_depasse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='sla_echeance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='sla_notification_envoyee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalincident',
            name='categorie',
            field=models.CharField(choices=[('Plomberie', 'Plomberie'), ('Electricite', 'Électricité'), ('Serrurerie', 'Serrurerie'), ('Climatisation', 'Climatisation'), ('Toiture', 'Toiture'), ('Informatique', 'Informatique'), ('Generateur', 'Générateur'), ('Vehicule', 'Véhicule'), ('Autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalincident',
            name='priorite',
            field=models.CharField(choices=[('critique', '🔴 Critique'), ('haute', '🟠 Haute'), ('moyenne', '🟡 Moyenne'), ('basse', '🟢 Basse')], default='moyenne', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalincident',
            name='statut',
            field=models.CharField(choices=[('declare', 'Déclaré'), ('assigne', 'Assigné'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('cloture', 'Clôturé'), ('annule', 'Annulé')], default='declare', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='auteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='categorie',
            field=models.CharField(choices=[('Plomberie', 'Plomberie'), ('Electricite', 'Électricité'), ('Serrurerie', 'Serrurerie'), ('Climatisation', 'Climatisation'), ('Toiture', 'Toiture'), ('Informatique', 'Informatique'), ('Generateur', 'Générateur'), ('Vehicule', 'Véhicule'), ('Autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='priorite',
            field=models.CharField(choices=[('critique', '🔴 Critique'), ('haute', '🟠 Haute'), ('moyenne', '🟡 Moyenne'), ('basse', '🟢 Basse')], default='moyenne', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='statut',
            field=models.CharField(choices=[('declare', 'Déclaré'), ('assigne', 'Assigné'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('cloture', 'Clôturé'), ('annule', 'Annulé')], default='declare', max_length=20),
        ),
        migrations.CreateModel(
            name='CommentaireIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_comment', models.CharField(choices=[('info', 'Information'), ('assignation', 'Assignation'), ('debut', 'Début intervention'), ('resolution', 'Résolution'), ('cloture', 'Clôture'), ('escalade', 'Escalade'), ('relance', 'Relance SLA')], default='info', max_length=20)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('photo_base64', models.TextField(blank=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='maintenance.incident')),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
    ]
