# Generated by Django 4.2.30 on 2026-09-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_ensure_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaireincident',
            name='type_comment',
            field=models.CharField(choices=[('info', 'Information'), ('assignation', 'Assignation'), ('debut', 'Début intervention'), ('photo_avant', '📷 Photo avant intervention'), ('photo_apres', '📷 Photo après intervention'), ('resolution', 'Résolution'), ('cloture', 'Clôture'), ('escalade', 'Escalade'), ('relance', 'Relance SLA')], default='info', max_length=20),
        ),
    ]
