# Generated by Django 4.2.30 on 2026-09-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_alter_commentaireincident_type_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalincident',
            name='statut',
            field=models.CharField(choices=[('declare', 'Déclaré'), ('assigne', 'Assigné'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('cloture', 'Clôturé'), ('annule', 'Annulé')], db_index=True, default='declare', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='statut',
            field=models.CharField(choices=[('declare', 'Déclaré'), ('assigne', 'Assigné'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('cloture', 'Clôturé'), ('annule', 'Annulé')], db_index=True, default='declare', max_length=20),
        ),
    ]
