# Generated by Django 4.2.30 on 2026-09-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_alter_historicalincident_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalincident',
            name='categorie',
            field=models.CharField(choices=[('Plomberie', 'Plomberie'), ('Electricite', 'Électricité'), ('Serrurerie', 'Serrurerie'), ('Climatisation', 'Climatisation'), ('Toiture', 'Toiture'), ('Proprete', 'Propreté'), ('Informatique', 'Informatique'), ('Generateur', 'Générateur'), ('Vehicule', 'Véhicule'), ('Autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='categorie',
            field=models.CharField(choices=[('Plomberie', 'Plomberie'), ('Electricite', 'Électricité'), ('Serrurerie', 'Serrurerie'), ('Climatisation', 'Climatisation'), ('Toiture', 'Toiture'), ('Proprete', 'Propreté'), ('Informatique', 'Informatique'), ('Generateur', 'Générateur'), ('Vehicule', 'Véhicule'), ('Autre', 'Autre')], max_length=50),
        ),
    ]
