# Generated by Django 4.2.30 on 2026-05-18 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restauration', '0002_historicalrepaslog_personnel_qrtoken_personnel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('boisson', 'Boisson'), ('snack', 'Snack'), ('hygiene', 'Hygiène'), ('cigarette', 'Cigarette'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('prix', models.DecimalField(decimal_places=0, default=0, max_digits=8)),
                ('stock', models.IntegerField(default=0)),
                ('unite', models.CharField(default='pièce', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsommationBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('montant', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('date_conso', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restauration.articleboutique')),
                ('personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='residences.personnel')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
