# Generated by Django 6.0.5 on 2026-05-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauration', '0003_add_boutique_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleboutique',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='articleboutique',
            name='categorie',
            field=models.CharField(default='autre', max_length=50),
        ),
        migrations.AlterField(
            model_name='articleboutique',
            name='nom',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='articleboutique',
            name='prix',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='articleboutique',
            name='unite',
            field=models.CharField(default='pièce', max_length=30),
        ),
    ]
