# Generated by Django 4.2.30 on 2026-05-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauration', '0003_add_boutique_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleboutique',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
