# Generated by Django 6.0.5 on 2026-05-24 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0005_demande_historicaldemande'),
        ('restauration', '0005_boutique_image_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(default=2026)),
                ('credit_initial', models.DecimalField(decimal_places=0, default=100000, max_digits=10)),
                ('credit_restant', models.DecimalField(decimal_places=0, default=100000, max_digits=10)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour', models.DateTimeField(auto_now=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_caisse', to='residences.personnel')),
            ],
            options={
                'ordering': ['-annee'],
                'unique_together': {('personnel', 'annee')},
            },
        ),
    ]
