# Generated by Django 4.2.30 on 2026-09-05 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0009_pointinteret'),
        ('restauration', '0008_consommationboutique_mode_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consommationboutique',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('bon', 'Bon de caisse'), ('credit', 'Crédit'), ('om', 'Orange Money'), ('wave', 'Wave'), ('mtn', 'MTN Money'), ('moov', 'Moov Money')], default='especes', max_length=20),
        ),
        migrations.CreateModel(
            name='AvisRestauration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repas', models.CharField(choices=[('matin', 'Petit déjeuner'), ('midi', 'Déjeuner'), ('soir', 'Dîner')], default='midi', max_length=20)),
                ('note', models.PositiveSmallIntegerField(default=5)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('date_avis', models.DateField(auto_now_add=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='residences.personnel')),
            ],
            options={
                'verbose_name': 'Avis restauration',
                'ordering': ['-date_creation'],
            },
        ),
    ]
