# Generated by Django 4.2.30 on 2026-09-06 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restauration', '0009_alter_consommationboutique_mode_paiement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemboursementBon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('om', 'Orange Money'), ('wave', 'Wave'), ('mtn', 'MTN Money'), ('moov', 'Moov Money')], max_length=10)),
                ('numero_telephone', models.CharField(blank=True, default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('bon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='restauration.boncaisse')),
                ('effectue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remboursement de bon',
                'ordering': ['-date_creation'],
            },
        ),
    ]
