# Generated by Django 4.2.30 on 2026-09-09 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restauration', '0010_remboursementbon'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAvis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('type_question', models.CharField(choices=[('etoiles', '⭐ Note en étoiles (1-5)'), ('texte', '💬 Texte libre'), ('oui_non', '✅ Oui / Non'), ('choix', '🔘 Choix parmi une liste')], default='etoiles', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('obligatoire', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Question d'avis",
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReponseAvis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_etoiles', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('valeur_texte', models.TextField(blank=True, default='')),
                ('valeur_choix', models.CharField(blank=True, default='', max_length=200)),
                ('valeur_oui_non', models.BooleanField(blank=True, null=True)),
                ('avis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='restauration.avisrestauration')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='restauration.questionavis')),
            ],
            options={
                'verbose_name': "Réponse d'avis",
            },
        ),
    ]
