# Generated by Django 4.2.30 on 2026-09-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauration', '0011_questionavis_reponseavis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consommationboutique',
            name='date_conso',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
