# Generated by Django 4.2.30 on 2026-10-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restauration", "0012_alter_consommationboutique_date_conso"),
    ]

    operations = [
        migrations.AddField(
            model_name="menujour",
            name="photo_base64",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Photo du plat en base64 — même mécanisme que les autres photos de l'application (Maintenance, Voyages), plus simple ici qu'exiger une URL d'image déjà hébergée ailleurs (image_url, gardé pour compatibilité).",
            ),
        ),
    ]
