# Generated by Django 6.0.5 on 2026-05-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='device_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('agent', 'Agent Terrain'), ('restauration', 'Equipe Restauration'), ('technicien', 'Technicien Maintenance'), ('menage', 'Equipe Ménage')], default='agent', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='societe',
            field=models.CharField(blank=True, default='ROXGOLD', max_length=100),
        ),
    ]
