# Generated by Django 6.0.5 on 2026-05-06 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0003_alter_batiment_options_and_more'),
        ('restauration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrepaslog',
            name='personnel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='residences.personnel'),
        ),
        migrations.AddField(
            model_name='qrtoken',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='residences.personnel'),
        ),
        migrations.AddField(
            model_name='qrtoken',
            name='type_repas',
            field=models.CharField(choices=[('petit_dejeuner', 'Petit-déjeuner'), ('dejeuner', 'Déjeuner'), ('diner', 'Dîner')], default='dejeuner', max_length=20),
        ),
        migrations.AddField(
            model_name='repaslog',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repas_pris', to='residences.personnel'),
        ),
        migrations.AlterField(
            model_name='qrtoken',
            name='genere_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_generes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qrtoken',
            name='residence',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
