# Generated by Django 6.0.5 on 2026-05-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauration', '0004_boutique_free_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleboutique',
            name='image_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
