# Generated by Django 6.0.5 on 2026-05-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvoyage',
            name='heure_depart',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='heure_depart',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
