# Generated by Django 6.0.5 on 2026-05-06 06:04

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence', models.CharField(max_length=20, unique=True)),
                ('bloc', models.CharField(max_length=30)),
                ('statut', models.CharField(choices=[('Libre', 'Libre'), ('Occupé', 'Occupé'), ('Réservé', 'Réservé'), ('Maintenance', 'Maintenance')], default='Libre', max_length=20)),
                ('occupant', models.CharField(blank=True, max_length=100, null=True)),
                ('societe', models.CharField(blank=True, max_length=100, null=True)),
                ('date_affectation', models.DateField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geojson_geometry', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bâtiment',
                'ordering': ['bloc', 'residence'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBatiment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('residence', models.CharField(db_index=True, max_length=20)),
                ('bloc', models.CharField(max_length=30)),
                ('statut', models.CharField(choices=[('Libre', 'Libre'), ('Occupé', 'Occupé'), ('Réservé', 'Réservé'), ('Maintenance', 'Maintenance')], default='Libre', max_length=20)),
                ('occupant', models.CharField(blank=True, max_length=100, null=True)),
                ('societe', models.CharField(blank=True, max_length=100, null=True)),
                ('date_affectation', models.DateField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geojson_geometry', models.JSONField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Bâtiment',
                'verbose_name_plural': 'historical Bâtiments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
