# Generated by Django 6.0.5 on 2026-05-09 21:02

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0004_alter_batiment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_demande', models.CharField(choices=[('reservation_residence', 'Réservation de résidence'), ('voyage', 'Planification de voyage'), ('maintenance', 'Signalement maintenance')], max_length=30)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('validee', "Validée par l'admin"), ('rejetee', "Rejetée par l'admin"), ('proposition', 'Proposition admin — En attente réponse'), ('acceptee', 'Proposition acceptée'), ('annulee', 'Annulée par le demandeur')], default='en_attente', max_length=20)),
                ('donnees', models.JSONField(default=dict)),
                ('residence_souhaitee', models.CharField(blank=True, max_length=20)),
                ('residence_attribuee', models.CharField(blank=True, max_length=20)),
                ('message_demandeur', models.TextField(blank=True)),
                ('commentaire_admin', models.TextField(blank=True)),
                ('proposition_admin', models.JSONField(blank=True, default=dict)),
                ('date_debut_souhaitee', models.DateField(blank=True, null=True)),
                ('date_fin_souhaitee', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_soumises', to=settings.AUTH_USER_MODEL)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDemande',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('type_demande', models.CharField(choices=[('reservation_residence', 'Réservation de résidence'), ('voyage', 'Planification de voyage'), ('maintenance', 'Signalement maintenance')], max_length=30)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('validee', "Validée par l'admin"), ('rejetee', "Rejetée par l'admin"), ('proposition', 'Proposition admin — En attente réponse'), ('acceptee', 'Proposition acceptée'), ('annulee', 'Annulée par le demandeur')], default='en_attente', max_length=20)),
                ('donnees', models.JSONField(default=dict)),
                ('residence_souhaitee', models.CharField(blank=True, max_length=20)),
                ('residence_attribuee', models.CharField(blank=True, max_length=20)),
                ('message_demandeur', models.TextField(blank=True)),
                ('commentaire_admin', models.TextField(blank=True)),
                ('proposition_admin', models.JSONField(blank=True, default=dict)),
                ('date_debut_souhaitee', models.DateField(blank=True, null=True)),
                ('date_fin_souhaitee', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(blank=True, editable=False)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('demandeur', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('traite_par', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Demande',
                'verbose_name_plural': 'historical Demandes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
