# Generated by Django 6.0.5 on 2026-05-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_historicalincident_photo_resolution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalincident',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='historicalincident',
            name='photo_resolution',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='photo_resolution',
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='photo_base64',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='photo_mime',
            field=models.CharField(blank=True, default='image/jpeg', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='photo_resolution_base64',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incident',
            name='photo_base64',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incident',
            name='photo_mime',
            field=models.CharField(blank=True, default='image/jpeg', max_length=50),
        ),
        migrations.AddField(
            model_name='incident',
            name='photo_resolution_base64',
            field=models.TextField(blank=True, default=''),
        ),
    ]
