# Generated by Django 6.0.5 on 2026-05-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalincident',
            name='photo_resolution',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='photo_resolution',
            field=models.ImageField(blank=True, null=True, upload_to='incidents/resolutions/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='incidents/%Y/%m/'),
        ),
    ]
