# Generated by Django 6.0.5 on 2026-05-09 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0001_initial'),
        ('residences', '0005_demande_historicaldemande'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('type_notif', models.CharField(choices=[('systeme', 'Système'), ('demande', 'Demande'), ('alerte', 'Alerte'), ('info', 'Info')], default='systeme', max_length=20)),
                ('lu', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simple_notifications', to='residences.personnel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simple_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_envoi'],
            },
        ),
    ]
