# Generated by Django 6.0.5 on 2026-05-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager Camp'), ('agent', 'Agent Terrain'), ('restauration', 'Restauration'), ('technicien', 'Technicien'), ('moyens_generaux', 'Patron Moyens Généraux'), ('resto_voyages', 'Chargé Restauration & Voyages')], default='agent', max_length=30),
        ),
    ]
