# Generated by Django 6.0.5 on 2026-05-25 09:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('induction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessBadge',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_code_data', models.TextField(blank=True, help_text='Base64 PNG du QR code')),
                ('qr_code_string', models.CharField(help_text='Identifiant unique encodé dans le QR', max_length=200, unique=True)),
                ('badge_pdf', models.FileField(blank=True, null=True, upload_to='induction/badges/')),
                ('badge_base64', models.TextField(blank=True, help_text='Badge PDF en base64')),
                ('statut', models.CharField(choices=[('actif', '✅ Actif'), ('expire', '❌ Expiré'), ('suspendu', '⚠️ Suspendu'), ('revoque', '🚫 Révoqué')], default='actif', max_length=20)),
                ('date_emission', models.DateField(default=django.utils.timezone.now)),
                ('date_expiration', models.DateField()),
                ('raison_revocation', models.TextField(blank=True)),
                ('date_revocation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Badge d'accès",
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_scanne', models.CharField(blank=True, max_length=200)),
                ('resultat', models.CharField(choices=[('autorise', '✅ Accès autorisé'), ('refuse', '❌ Accès refusé'), ('expire', '⏰ Badge expiré'), ('inconnnu', '❓ Inconnu'), ('urgence', '🚨 Accès urgence')], default='refuse', max_length=20)),
                ('raison_refus', models.CharField(blank=True, max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': "Log d'accès",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('categorie', models.CharField(choices=[('identite', "Pièce d'identité"), ('medical', 'Document médical'), ('formation', 'Certification formation'), ('contrat', 'Contrat / Convention'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('obligatoire', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('validite_jours', models.PositiveIntegerField(blank=True, help_text="Validité en jours (null = pas d'expiration)", null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Type de document',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('relation', models.CharField(help_text='Ex: Épouse, Parent, Ami', max_length=100)),
                ('telephone', models.CharField(max_length=50)),
                ('telephone_2', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': "Contact d'urgence",
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='induction/documents/%Y/%m/')),
                ('nom_fichier', models.CharField(blank=True, max_length=255)),
                ('taille_ko', models.PositiveIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('fichier_base64', models.TextField(blank=True, default='')),
                ('date_emission', models.DateField(blank=True, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('numero_doc', models.CharField(blank=True, help_text='Numéro de passeport, CNI, etc.', max_length=100)),
                ('statut', models.CharField(choices=[('soumis', 'Soumis — en attente de validation'), ('valide', 'Validé par RH'), ('refuse', 'Refusé'), ('expire', 'Expiré')], default='soumis', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Document employé',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('non_commence', 'Non commencé'), ('en_cours', 'En cours'), ('complete', 'Terminé'), ('expire', 'Expiré')], default='non_commence', max_length=20)),
                ('progression', models.PositiveIntegerField(default=0, help_text='0-100%')),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('temps_passe_min', models.PositiveIntegerField(default=0)),
                ('certification_valide_jusqu', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Formation employé',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InductionWorkflow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('non_commence', '⬜ Non commencé'), ('enregistrement', '📝 Enregistrement'), ('documents', '📄 Documents'), ('formation', '🎓 Formation'), ('quiz', '📋 Quiz'), ('medical', '🏥 Visite médicale'), ('validation', '✅ Validation finale'), ('complet', '🎉 Induction complète'), ('refuse', '❌ Refusé'), ('expire', '⏰ Expiré')], default='non_commence', max_length=20)),
                ('etape_enregistrement', models.BooleanField(default=False)),
                ('etape_documents', models.BooleanField(default=False)),
                ('etape_formation', models.BooleanField(default=False)),
                ('etape_quiz', models.BooleanField(default=False)),
                ('etape_medical', models.BooleanField(default=False)),
                ('date_enregistrement', models.DateTimeField(blank=True, null=True)),
                ('date_documents', models.DateTimeField(blank=True, null=True)),
                ('date_formation', models.DateTimeField(blank=True, null=True)),
                ('date_quiz', models.DateTimeField(blank=True, null=True)),
                ('date_medical', models.DateTimeField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('raison_refus', models.TextField(blank=True)),
                ('notes_admin', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Workflow induction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalCheck',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='°C', max_digits=4, null=True)),
                ('tension_systolique', models.PositiveIntegerField(blank=True, help_text='mmHg', null=True)),
                ('tension_diastolique', models.PositiveIntegerField(blank=True, help_text='mmHg', null=True)),
                ('pouls', models.PositiveIntegerField(blank=True, help_text='bpm', null=True)),
                ('test_alcool', models.BooleanField(default=False, help_text='Test alcool positif')),
                ('taux_alcool', models.DecimalField(blank=True, decimal_places=2, help_text='g/L', max_digits=4, null=True)),
                ('test_drogue', models.BooleanField(default=False, help_text='Test drogue positif')),
                ('substances_detectees', models.CharField(blank=True, max_length=500)),
                ('probleme_cardiaque', models.BooleanField(default=False)),
                ('diabete', models.BooleanField(default=False)),
                ('epilepsie', models.BooleanField(default=False)),
                ('hypertension', models.BooleanField(default=False)),
                ('medicaments_en_cours', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('resultat', models.CharField(choices=[('FIT', '✅ Apte — accès autorisé'), ('UNFIT', '❌ Inapte — accès interdit'), ('PENDING', '⏳ En attente de résultats')], default='PENDING', max_length=10)),
                ('observations', models.TextField(blank=True)),
                ('recommandations', models.TextField(blank=True)),
                ('medecin_nom', models.CharField(blank=True, max_length=200)),
                ('medecin_matricule', models.CharField(blank=True, max_length=100)),
                ('signature_medecin', models.TextField(blank=True, help_text='Signature base64')),
                ('date_examen', models.DateField(default=django.utils.timezone.now)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('validite_jours', models.PositiveIntegerField(default=365)),
            ],
            options={
                'verbose_name': 'Visite médicale',
                'ordering': ['-date_examen'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_correcte', models.BooleanField(default=False)),
                ('temps_reponse_s', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Réponse quiz',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_tentative', models.PositiveIntegerField(default=1)),
                ('score', models.DecimalField(decimal_places=2, default=0, help_text='Score en %', max_digits=5)),
                ('points_obtenus', models.PositiveIntegerField(default=0)),
                ('points_total', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('reussi', 'Réussi'), ('echoue', 'Échoué')], default='en_cours', max_length=20)),
                ('score_minimum', models.PositiveIntegerField(default=80, help_text='Score minimum requis pour réussir (%)')),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('duree_secondes', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tentative quiz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=500)),
                ('est_correcte', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Choix de réponse',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texte', models.TextField(help_text='Texte de la question')),
                ('explication', models.TextField(blank=True, help_text='Explication de la bonne réponse')),
                ('points', models.PositiveIntegerField(default=1)),
                ('niveau', models.CharField(choices=[('facile', 'Facile'), ('moyen', 'Moyen'), ('difficile', 'Difficile')], default='moyen', max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='induction/quiz/')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Question quiz',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('type_formation', models.CharField(choices=[('video', 'Vidéo'), ('pdf', 'Document PDF'), ('presentation', 'Présentation'), ('mixte', 'Format mixte')], default='mixte', max_length=20)),
                ('duree_estimee_min', models.PositiveIntegerField(default=30, help_text='Durée en minutes')),
                ('obligatoire', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
            ],
            options={
                'verbose_name': 'Formation',
                'ordering': ['ordre', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=300)),
                ('type_media', models.CharField(choices=[('video', 'Vidéo'), ('pdf', 'Document PDF'), ('presentation', 'Présentation'), ('mixte', 'Format mixte')], default='pdf', max_length=20)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='induction/formations/%Y/')),
                ('url_externe', models.URLField(blank=True, help_text='URL YouTube, Vimeo, etc.')),
                ('contenu_html', models.TextField(blank=True, help_text='Contenu HTML inline')),
                ('duree_min', models.PositiveIntegerField(default=10)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('obligatoire', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Module de formation',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('etape_complete', 'Étape complétée'), ('document_valide', 'Document validé'), ('document_refuse', 'Document refusé'), ('quiz_reussi', 'Quiz réussi'), ('quiz_echoue', 'Quiz échoué'), ('medical_fit', 'Médical FIT'), ('medical_unfit', 'Médical UNFIT'), ('badge_genere', 'Badge généré'), ('acces_autorise', 'Accès autorisé'), ('acces_refuse', 'Accès refusé'), ('badge_revoque', 'Badge révoqué'), ('workflow_reset', 'Workflow réinitialisé')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Événement workflow',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='contractor',
            options={'ordering': ['nom'], 'verbose_name': 'Sous-traitant', 'verbose_name_plural': 'Sous-traitants'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['nom', 'prenom'], 'verbose_name': 'Employé', 'verbose_name_plural': 'Employés'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['nom'], 'verbose_name': 'Site minier', 'verbose_name_plural': 'Sites miniers'},
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='induction_e_email_108929_idx',
            old_name='emp_email_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='induction_e_site_id_95931c_idx',
            old_name='emp_site_statut_idx',
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='induction/photos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='camp',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='genre',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', "En cours d'induction"), ('valide', 'Validé — accès autorisé'), ('refuse', 'Refusé — accès interdit'), ('expire', 'Expiré'), ('suspendu', 'Suspendu')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='site',
            name='badge_validite_j',
            field=models.PositiveIntegerField(default=365, help_text='Validité badge en jours'),
        ),
        migrations.AlterField(
            model_name='site',
            name='code',
            field=models.CharField(help_text='Ex: SGO-01', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='site',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='site',
            name='medical_validite_j',
            field=models.PositiveIntegerField(default=365, help_text='Validité médicale en jours'),
        ),
        migrations.AlterField(
            model_name='site',
            name='quiz_score_min',
            field=models.PositiveIntegerField(default=80, help_text='Score minimum quiz QHSE (%)'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zone',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='camp',
            unique_together={('site', 'code')},
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['matricule'], name='induction_e_matricu_59fa71_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['type_employe'], name='induction_e_type_em_a29eea_idx'),
        ),
        migrations.AddField(
            model_name='accessbadge',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessbadge',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='induction.employee'),
        ),
        migrations.AddField(
            model_name='accessbadge',
            name='revoque_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges_revoques', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessbadge',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='induction.site'),
        ),
        migrations.AddField(
            model_name='accessbadge',
            name='zones_autorisees',
            field=models.ManyToManyField(blank=True, to='induction.zone'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='agent_scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans_effectues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acces', to='induction.accessbadge'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_acces', to='induction.employee'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='induction.site'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='induction.zone'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_urgence', to='induction.employee'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='induction.employee'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='type_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='induction.documenttype'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeetraining',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeetraining',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='induction.employee'),
        ),
        migrations.AddField(
            model_name='inductionworkflow',
            name='badge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow', to='induction.accessbadge'),
        ),
        migrations.AddField(
            model_name='inductionworkflow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inductionworkflow',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='induction.employee'),
        ),
        migrations.AddField(
            model_name='inductionworkflow',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='induction.site'),
        ),
        migrations.AddField(
            model_name='medicalcheck',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalcheck',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites_medicales', to='induction.employee'),
        ),
        migrations.AddField(
            model_name='medicalcheck',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='induction.site'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='induction.employee'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='induction.site'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='supervise_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_supervises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='tentative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='induction.quizattempt'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='choix_selectionne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='induction.quizchoice'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='sites',
            field=models.ManyToManyField(blank=True, to='induction.site'),
        ),
        migrations.AddField(
            model_name='quizchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='induction.quizquestion'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='induction.quizquestion'),
        ),
        migrations.AddField(
            model_name='training',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='training',
            name='sites',
            field=models.ManyToManyField(blank=True, related_name='formations', to='induction.site'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='induction.training'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives', to='induction.training'),
        ),
        migrations.AddField(
            model_name='employeetraining',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='induction.training'),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='induction.training'),
        ),
        migrations.AddField(
            model_name='employeetraining',
            name='modules_completes',
            field=models.ManyToManyField(blank=True, to='induction.trainingmodule'),
        ),
        migrations.AddField(
            model_name='workflowevent',
            name='effectue_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowevent',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='induction.inductionworkflow'),
        ),
        migrations.AddIndex(
            model_name='accessbadge',
            index=models.Index(fields=['qr_code_string'], name='induction_a_qr_code_58c39c_idx'),
        ),
        migrations.AddIndex(
            model_name='accessbadge',
            index=models.Index(fields=['employee', 'statut'], name='induction_a_employe_537518_idx'),
        ),
        migrations.AddIndex(
            model_name='accessbadge',
            index=models.Index(fields=['date_expiration'], name='induction_a_date_ex_bf1e11_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['employee', 'timestamp'], name='induction_a_employe_7dffa6_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['site', 'resultat'], name='induction_a_site_id_316613_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['timestamp'], name='induction_a_timesta_7b749c_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['employee', 'statut'], name='induction_e_employe_1acc5e_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['date_expiration'], name='induction_e_date_ex_367c83_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalcheck',
            index=models.Index(fields=['employee', 'resultat'], name='induction_m_employe_af798b_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalcheck',
            index=models.Index(fields=['date_expiration'], name='induction_m_date_ex_90d99a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizanswer',
            unique_together={('tentative', 'question')},
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['employee', 'statut'], name='induction_q_employe_2b10b1_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['formation', 'employee'], name='induction_q_formati_653caa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeetraining',
            unique_together={('employee', 'formation')},
        ),
    ]
